### ISSUE TITLE
vcollide_wireframe 1 doesn't show info_ff_script collisions in current build

### ISSUE THREAD

**Issue by gumbuknine** [fortressforever-2013/FortressForever2013-src#15]

**Comment by YoYo-178** [comment]
SDK 2013 only draws wireframes on props that are actually solid, and not on props that are "transparent" (player can walk through it). So this behaviour actually seems pretty normal to me, but anyway now one can do `vcollide_wireframe 2` to replicate the SDK 2006 behavior.
