### ISSUE TITLE
[Linux] Weapon selection crashes the game as certain classes in fullscreen

### ISSUE THREAD

**Issue by YoYo178** [fortressforever-2013/FortressForever2013-src#19]

**Comment by YoYo178** [comment]
Gonna merge this into #12

**Comment by fryl0ch** [comment]
this still happens for me at resolutions > 1200 vertical
seems to happen as any class, windowed mode included

**Comment by fryl0ch** [comment]
the crash i was expericing may not have been the same as the original issue...

i narrowed this down to ./resource/ItemGlyphs.ttf, if i replace this in ClientScheme.res the crash doesn't happen

found this: https://developer.valvesoftware.com/wiki/Authoring_and_Using_TrueType_Fonts#Linux_Support

i'll see if i can clamp the size of the icons when yres >= 1200
