### ISSUE TITLE
VGUI Panels have blocky corners on low alpha value

### ISSUE THREAD

**Issue by YoYo-178** [fortressforever-2013/FortressForever2013-src#7]
(OLD TITLE - Weapon selection icons have blocky corners)

happens after it starts fading
the selected weapon's icon also turns blocky eventually
also seen for a few frames when opening the weapon selection
![image](https://github.com/fortressforever-2013/FortressForever2013-src/assets/95132723/8c7a4a36-c347-414b-aea9-65e1ce364359)

**Comment by azzyr** [comment]
issue with panel::drawbox when alpha is below 133. wtf?

**Comment by azzyr** [comment]
fixed, corner materials used both $alphatest and $translucent for some reason???
